"""Deterministic local lexical, semantic, and hybrid retrieval."""

from localml_scholar.retrieval.bm25 import BM25Config
from localml_scholar.retrieval.chunking import (
    ChunkingConfig,
    chunk_document,
    validate_chunk_coverage,
)
from localml_scholar.retrieval.documents import (
    Chunk,
    Citation,
    Document,
    PageText,
    Section,
)
from localml_scholar.retrieval.hybrid import (
    HybridRetrievalConfig,
    RerankingConfig,
    fuse_rankings,
    maximum_positive_normalization,
    reranking_features,
    source_range_overlap,
    weighted_reranking_score,
)
from localml_scholar.retrieval.index import (
    IndexConfig,
    RetrievalIndex,
    SearchFilters,
    SearchQuery,
    SearchResult,
    highlight_matches,
)
from localml_scholar.retrieval.ingestion import (
    ingest_file,
    ingest_files,
    ingest_markdown,
    ingest_pdf_text,
    ingest_plain_text,
)
from localml_scholar.retrieval.metrics import (
    RetrievalEvaluation,
    average_precision,
    evaluate_rankings,
    hit_rate_at_k,
    mean_relevant_rank,
    ndcg_at_k,
    precision_at_k,
    recall_at_k,
    reciprocal_rank,
)
from localml_scholar.retrieval.semantic import (
    SemanticIndex,
    SemanticQueryProjection,
    SemanticRetrievalConfig,
    build_tfidf_matrix,
    canonicalize_svd_signs,
    fit_lsa,
    vocabulary_sha256,
)
from localml_scholar.retrieval.text import (
    LexicalTerm,
    LexicalTokenizerConfig,
    lexical_terms,
    tokenize_lexically,
)

__all__ = [
    "BM25Config",
    "average_precision",
    "Chunk",
    "ChunkingConfig",
    "Citation",
    "Document",
    "evaluate_rankings",
    "fit_lsa",
    "fuse_rankings",
    "highlight_matches",
    "hit_rate_at_k",
    "IndexConfig",
    "ingest_file",
    "ingest_files",
    "ingest_markdown",
    "ingest_pdf_text",
    "ingest_plain_text",
    "LexicalTerm",
    "LexicalTokenizerConfig",
    "lexical_terms",
    "PageText",
    "precision_at_k",
    "recall_at_k",
    "reciprocal_rank",
    "RetrievalEvaluation",
    "RetrievalIndex",
    "HybridRetrievalConfig",
    "maximum_positive_normalization",
    "mean_relevant_rank",
    "ndcg_at_k",
    "RerankingConfig",
    "reranking_features",
    "SearchFilters",
    "SearchQuery",
    "SearchResult",
    "SemanticIndex",
    "SemanticQueryProjection",
    "SemanticRetrievalConfig",
    "Section",
    "tokenize_lexically",
    "source_range_overlap",
    "weighted_reranking_score",
    "build_tfidf_matrix",
    "canonicalize_svd_signs",
    "vocabulary_sha256",
    "validate_chunk_coverage",
    "chunk_document",
]
