"""Deterministic source-linked scholarly analysis."""

from localml_scholar.scholarly.artifacts import (
    build_reproduction_checklist,
    build_structured_summary,
    compare_analyses,
    identify_research_gaps,
    render_checklist_markdown,
    render_comparison_markdown,
    render_notation_markdown,
)
from localml_scholar.scholarly.config import ScholarlyConfig
from localml_scholar.scholarly.equations import (
    analyze_equation_links,
    build_notation_glossary,
    detect_equation_blocks,
    extract_definition_candidates,
    normalize_equation,
    symbol_spans,
)
from localml_scholar.scholarly.evaluation import (
    ExtractionMetrics,
    citation_coverage,
    classification_accuracy,
    extraction_metrics,
)
from localml_scholar.scholarly.models import (
    ChecklistItem,
    ComparisonDimension,
    DefinitionCandidate,
    EquationAnalysis,
    EquationBlock,
    ExperimentRecord,
    ExtractedTable,
    NotationEntry,
    Paper,
    PaperAnalysis,
    PaperComparison,
    PaperSection,
    Procedure,
    ReproductionChecklist,
    ResearchGapCandidate,
    RiskFlag,
    ScholarlyEvidence,
    ScholarlySearchResult,
    SourceCitation,
    StructuredSummary,
    SummaryField,
)
from localml_scholar.scholarly.pipeline import ScholarlyAnalysisPipeline
from localml_scholar.scholarly.retrieval import equation_aware_search
from localml_scholar.scholarly.serialization import (
    SCHOLARLY_ARTIFACT_FORMAT_VERSION,
    ScholarlyArtifact,
    create_artifact,
    load_analysis,
    load_artifact,
    save_analysis,
    save_artifact,
    validate_artifact,
)
from localml_scholar.scholarly.source import (
    citation_for_range,
    section_for_range,
    validate_source_citation,
)

__all__ = [
    "SCHOLARLY_ARTIFACT_FORMAT_VERSION",
    "ChecklistItem",
    "ComparisonDimension",
    "DefinitionCandidate",
    "EquationAnalysis",
    "EquationBlock",
    "ExperimentRecord",
    "ExtractedTable",
    "ExtractionMetrics",
    "NotationEntry",
    "Paper",
    "PaperAnalysis",
    "PaperComparison",
    "PaperSection",
    "Procedure",
    "ReproductionChecklist",
    "ResearchGapCandidate",
    "RiskFlag",
    "ScholarlyAnalysisPipeline",
    "ScholarlyArtifact",
    "ScholarlyConfig",
    "ScholarlyEvidence",
    "ScholarlySearchResult",
    "SourceCitation",
    "StructuredSummary",
    "SummaryField",
    "analyze_equation_links",
    "build_notation_glossary",
    "build_reproduction_checklist",
    "build_structured_summary",
    "citation_coverage",
    "citation_for_range",
    "classification_accuracy",
    "compare_analyses",
    "create_artifact",
    "detect_equation_blocks",
    "equation_aware_search",
    "extract_definition_candidates",
    "extraction_metrics",
    "identify_research_gaps",
    "load_analysis",
    "load_artifact",
    "normalize_equation",
    "render_checklist_markdown",
    "render_comparison_markdown",
    "render_notation_markdown",
    "save_analysis",
    "save_artifact",
    "section_for_range",
    "symbol_spans",
    "validate_artifact",
    "validate_source_citation",
]
